name: Release

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            rid: "osx-x64"
            os: macos-13
          - target: aarch64-apple-darwin
            rid: "osx-arm64"
            os: macos-14
          - target: x86_64-pc-windows-gnu
            rid: "win-x64"
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            rid: linux-x64
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: build
        run: |
          dotnet --version

          # dotnet dev-certs https --clean -q
          # dotnet dev-certs https --trust -q
          # dotnet dev-certs https --check -q

          # dotnet build -c Release --self-contained true
          # dotnet publish -c Release --self-contained true

          # dotnet build -c Release
          dotnet publish -c Release --self-contained true

          mkdir dist

          cp ./bin/Release/net9.0/${{ matrix.rid }}/publish/jint-cli ./dist

          # cp ./bin/Release/net9.0/jint-cli.dll ./dist/jint-cli.dll
          tar -czf ./jint-cli-${{ matrix.target }}.tar.gz -C dist .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: jint-cli-${{ matrix.target }}
          path: ./jint-cli-${{ matrix.target }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: jint-cli
          pattern: jint-cli*
          merge-multiple: true

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "jint-cli/*.tar.gz"
          allowUpdates: true
